
title: SeungWon Seo #Your awesome title
email: ssw03270@khu.ac.kr #youremail@domain.com
description: > # this means to ignore newlines until "baseurl"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: # the subpath of the site
url: https://sse03270.github.io/ #http://starry99.github.io/catbook # the base hostname & protocol for your site

permalink: /:year-:month/:title
timezone:

favicon: /assets/img/favicon.ico

google_analytics: #UA—XXXXXXXX-X
disqus_shortname: #disqus shortname
cusdis:
    app_id: #your cusdis app_id

user:
  name: SeungWon Seo
  pic: /assets/img/me_resize.jpg
  picAlt: "catbook"
  job: Undergraduate Researcher<br>IIIXR LAB<br>Department of Software Convergence<br>Kyung Hee University
  aboutme: true # comment this out if you don't need the 'about' page.

exclude:
  - README.md
  - LICENSE
  - github

defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comment: true   

markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown 

# Filtering Content
show_drafts: null
limit_posts: 0
future:      false
unpublished: false
