# Setup
title:               SeungWon Seo
tagline:             'Development Blog'
description:         '글 쓰기를 좋아합니다. 앞으로는 개발이나 연구 관련으로도 적어볼 계획입니다. Made by <a href="https://www.instagram.com/won_yee_/" target="_blank">@won_yee_</a>.'
url:                 https://ssw03270.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              SeungWon Seo
  url:               https://www.instagram.com/won_yee_/
  email:             ssw03270@khu.ac.kr

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
